import type {Metadata} from "next";
import "./globals.scss";
import Script from "next/script";
import {Header} from "@/components/Header/Header";
import {Footer} from "@/components/Footer/Footer";
import { PopupProvider } from '@/context/PopupContext';
import type {Viewport} from 'next'
const mangoId = process.env.NEXT_PUBLIC_MANGO_ID;

export const viewport: Viewport = {
  themeColor: '#cdc5bf', // Цвет верхней полоски в мобильных браузерах
  width: 'device-width',
  initialScale: 1,
 /* maximumScale: 1, // Опционально: запрещает зум (хорошо для фиксированных слайдеров)
  userScalable: true,*/
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; //TODO отредактировать метадату для сео на каждой странице

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
    <body>
    <PopupProvider>
    <Header/>
    {children}
    <Footer/>
    </PopupProvider>
    {/* Mango Office Widget */}

    </body>
    </html>
  );
}
