import type { Metadata } from "next";
import "./globals.scss";
import {Header} from "@/components/Header/Header";
import {Footer} from "@/components/Footer/Footer";
import type { Viewport } from 'next'

export const viewport: Viewport = {
  themeColor: '#cdc5bf', // Цвет верхней полоски в мобильных браузерах
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1, // Опционально: запрещает зум (хорошо для фиксированных слайдеров)
  userScalable: false,
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; //TODO отредактировать метадату для сео на каждой странице

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body >
      <Header />
        {children}
      <Footer />
      </body>
    </html>
  );
}
