import type { Metadata } from "next";
import "./globals.scss";
import {Header} from "@/components/Header/Header";
import {Footer} from "@/components/Footer/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; //TODO отредактировать метадату для сео на каждой странице

import { montserrat, pacifico } from "./fonts";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru"
          className={[
            pacifico.variable,
            montserrat.variable,
          ].join(" ")}>
      <body  className={montserrat.variable} >
      <Header />
        {children}
      <Footer />
      </body>
    </html>
  );
}
